require "rails_helper"

RSpec.describe GoogleService do
  let(:service) { GoogleService.new }
  let(:landmarks) { TomTomService.category_search(categorySet: 7367).map {|landmark| landmark[:poi][:name]} }
  let(:expected) { ["ChIJMT6TsdR4bIcR3WqJ91M7Kec", "ChIJvSwKotR4bIcRZbh-oehYci0"] }

  it 'exist' do
    expect(service).to be_a GoogleService
  end

  it "#landmarks_place_ids returns an array of place_id for landmarks generated by TomTomService" do
    VCR.use_cassette('google_service_landmarks_place_ids_instance_method') do
      results = landmarks.map do |landmark|
        service.landmarks_place_ids(landmark)
      end

      expect(results.class).to eq(Array)
      expect(results.first).to eq(expected[0])
      expect(results.second).to eq(expected[1])
    end
  end

  it "::landmarks_place_ids returns an array of place_id for landmarks generated by TomTomService" do
    VCR.use_cassette('google_service_landmarks_place_ids_class_method') do
      results = landmarks.map do |landmark|
        GoogleService.landmarks_place_ids(landmark)
      end

      expect(results.class).to eq(Array)
      expect(results.first).to eq(expected[0])
      expect(results.second).to eq(expected[1])
    end
  end

  it "#get_details(id) returns landmark's details when given a place_id" do
    VCR.use_cassette('google_service_get_details_instance_method') do
      result = service.get_details(expected[0])

      expect(result).to have_key(:formatted_address)
      expect(result).to have_key(:formatted_phone_number)
      expect(result).to have_key(:geometry)
      expect(result).to have_key(:name)
      expect(result).to have_key(:photos)
      expect(result).to have_key(:website)
      expect(result[:place_id]).to eq(expected[0])
    end
  end

  it "::get_details(id) returns landmark's details when given a place_id" do
    VCR.use_cassette('google_service_get_details_class_method') do
      result = GoogleService.get_details(expected[0])

      expect(result).to have_key(:formatted_address)
      expect(result).to have_key(:formatted_phone_number)
      expect(result).to have_key(:geometry)
      expect(result).to have_key(:name)
      expect(result).to have_key(:photos)
      expect(result).to have_key(:website)
      expect(result[:place_id]).to eq(expected[0])
    end
  end
end
